sudo: false

branches:
  only:
    - master

language: groovy
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  apt:
    packages:
    - praat
    - sox

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/files-2.1
    - $HOME/.gradle/wrapper
